POST http://localhost:8046/api/v1/addAsset HTTP/1.1
content-type: application/json

{
  "assetURL": "https://rumble.com/v1lf51r-cultdao-in-100-seconds-michael-saylor-talks-about-cult.html",
  "description": "example description",
  "signature": "publicdemokey"
}
